name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t vkanamuk/wisecow:$GITHUB_SHA .
          docker push vkanamuk/wisecow:$GITHUB_SHA

      - name: Deploy to Kubernetes
        uses: appleboy/kubectl-action@v0.1.3
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          commands: |
            kubectl apply -f kubernetes/deployment.yml
            kubectl apply -f kubernetes/service.yml
            kubectl apply -f kubernetes/ingress.yml

